apiVersion: v1
kind: PersistentVolume
metadata:
  name: ba-database-pv
  labels:
    type: glusterfs
    name: ba-database-storage
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  glusterfs: 
    endpoints: glusterfs-cluster 
    path: ba-database
    readOnly: false
