apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ba-database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: ba-database-storage
